apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: mysql
    type: database
    team: db_admins
    provider: oracle
spec:
  containers:
    - name: mysql
      image: mysql:8
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: toor
      volumeMounts:
        - name: volume01
          mountPath: /var/lib/mysql
  volumes:
    - name: volume01
      hostPath:
        path: /data/mysql
