apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod1
  name: pod1
spec:
  containers:
    - image: repository/application:1.0
      name: pod1
      envFrom:
        - configMapRef:
            name: config1
        - secretRef:
            name: secret1
      volumeMounts:
        - mountPath: /data/configs/
          name: configmap1-volume
        - mountPath: /data/secrets/
          name: secret1-volume
  volumes:
    - name: configmap1-volume
      configMap:
        name: config2
    - name: secret1-volume
      secret:
        secretName: secret2