version: '3.7'

services:

  mongodb:
    container_name: mongodb
    image: mongo:4.4.5-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    ports:
      - 27017:27017
    networks:
      - session3

  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3306:3306
    networks:
      - session3

networks:
  session3:
    name: session3
